
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import AztecAnchorContractArtifactJson from '../../target/aztec_anchor-AztecAnchor.json' with { type: 'json' };
export const AztecAnchorContractArtifact = loadContractArtifact(AztecAnchorContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AztecAnchor;
 */
export class AztecAnchorContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, AztecAnchorContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, AztecAnchorContract.artifact, wallet) as Promise<AztecAnchorContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<AztecAnchorContract>(PublicKeys.default(), wallet, AztecAnchorContractArtifact, AztecAnchorContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<AztecAnchorContract>(publicKeys, wallet, AztecAnchorContractArtifact, AztecAnchorContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AztecAnchorContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AztecAnchorContract['methods'][M]>
  ) {
    return new DeployMethod<AztecAnchorContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AztecAnchorContractArtifact,
      AztecAnchorContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AztecAnchorContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AztecAnchorContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'proof_registry' | 'proof_count'> {
      return {
        proof_registry: {
      slot: new Fr(1n),
    },
proof_count: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'proof_registry' | 'proof_count'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** anchor_proof(doc_hash: array, artifact_hash: array, signer_fpr: array, tl_root: array, tl_root_eu: array, eu_trust_enabled: boolean) */
    anchor_proof: ((doc_hash: (bigint | number)[], artifact_hash: (bigint | number)[], signer_fpr: (bigint | number)[], tl_root: (bigint | number)[], tl_root_eu: (bigint | number)[], eu_trust_enabled: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor() */
    constructor: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proof_count() */
    get_proof_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proof_exists(doc_hash: array, signer_fpr: array) */
    get_proof_exists: ((doc_hash: (bigint | number)[], signer_fpr: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proof_id_for(doc_hash: array, signer_fpr: array) */
    get_proof_id_for: ((doc_hash: (bigint | number)[], signer_fpr: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
